# Generated by Django 3.0.8 on 2020-08-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200828_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bla_bla_bla',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
